version: "3.7"
name: "poc-nlb-bff"

services:
    db:
        build:
            context: ./db/
        # image: mcr.microsoft.com/mssql/server
        hostname: mssql
        environment:
            - ACCEPT_EULA=Y
            - MSSQL_SA_PASSWORD=P@ssw0rd
        ports:
            - "1453:1433"
        # volumes:
        #     - ./db/bak/:/var/opt/mssql/backup/
        networks:
            - net-backend

    webApp1:
        depends_on:
            - db
        # build:
        #     context: ./FrontendHost
        image: bff-test
        ports:
            - "44447:443"
        # - "44447:80"
        environment:
            - ASPNETCORE_URLS=https://+:443;http://+:80
            - ASPNETCORE_Kestrel__Certificates__Default__Password=P@ssw0rd
            - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
        volumes:
            - ./cert:/https:ro
        networks:
            - net-backend
            - net-frontend

    webApp2:
        depends_on:
            - db
        # build:
        #     context: ./FrontendHost
        image: bff-test
        ports:
            - "44457:443"
            # - "44457:80"
        environment:
            - ASPNETCORE_URLS=https://+:443;http://+:80
            - ASPNETCORE_Kestrel__Certificates__Default__Password=P@ssw0rd
            - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
        volumes:
            - ./cert:/https:ro
        networks:
            - net-backend
            - net-frontend

    # nlb:
    #     -
#     healthcheck:
# test: ["CMD", "curl", "-f", "http://localhost:8080/utility/healthcheck"]
# interval: 30s
# timeout: 10s
# retries: 3
    nginx:
        build:
            context: .
            dockerfile: ./nlb/Dockerfile
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./nlb:/etc/nginx/conf.d/
        networks:
            - net-frontend
        depends_on:
            - webApp1
            - webApp2

networks:
    net-backend:
    net-frontend: